### ISSUE TITLE
Review implementation of ISO and IEC NISO STS output according to guide

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#190]
ISO and IEC published a Guidance document on their implementation of NISO STS, both contains differences from each other. We need to confirm that our output (and for input conversion) conforms to both in their respective flavors.

[Guidelines for coding IEC and ISO standards in NISOSTS.pdf](https://github.com/metanorma/mnconvert/files/9429314/Guidelines.for.coding.IEC.and.ISO.standards.in.NISOSTS.pdf)

**Comment by Intelligent2013** [comment]
TODO list (draft, will be updated):
- [x] Regenerate id with ISO/IEC Guidelines (https://github.com/metanorma/mnconvert/issues/193)
- [x] ISO is using underscores in IDs, IEC is using dashes (https://github.com/metanorma/mnconvert/issues/197)
- [x] Metadata element (https://github.com/metanorma/mnconvert/issues/198)
- [x] Copyright statements (https://github.com/metanorma/mnconvert/issues/199)
- [x] Foreword encoding (https://github.com/metanorma/mnconvert/issues/200)
- [x] Introduction encoding (https://github.com/metanorma/mnconvert/issues/201)
- [x] Amendment's label for ISO (https://github.com/metanorma/mnconvert/issues/202)
- [x] Types of clause (https://github.com/metanorma/mnconvert/issues/203)
- [x] Annex's id format (https://github.com/metanorma/mnconvert/issues/204)
- [x] Annex content-type (https://github.com/metanorma/mnconvert/issues/205)
- [x] Bibliography id (https://github.com/metanorma/mnconvert/issues/206)
- [ ] ISO/IEC Coding Guidelines: Multiple lists inside bibliography (https://github.com/metanorma/mnconvert/issues/207)
- [x] ISO/IEC Coding Guidelines: Index (https://github.com/metanorma/mnconvert/issues/208)
- [x] ISO/IEC Coding Guidelines: add non-breaking spaces (https://github.com/metanorma/mnconvert/issues/209)
- [x] ISO/IEC Coding Guidelines: alignment of p (https://github.com/metanorma/mnconvert/issues/211)
- [x] ISO/IEC Coding Guidelines: mark up additions and deletions (https://github.com/metanorma/mnconvert/issues/212)
- [x] ISO/IEC Coding Guidelines: Warning, Important, Caution (https://github.com/metanorma/mnconvert/issues/213)
- [x] ISO/IEC Coding Guidelines: List's type (https://github.com/metanorma/mnconvert/issues/214)
- [x] ISO/IEC Coding Guidelines: lists are coded outside the preceding p (https://github.com/metanorma/mnconvert/issues/215)
- [x] ISO/IEC Coding Guidelines: Table without borders (https://github.com/metanorma/mnconvert/issues/216)
- [x] ISO/IEC Coding Guidelines: graphic attributes (https://github.com/metanorma/mnconvert/issues/217)
- [x] ISO/IEC Coding Guidelines: code and preformatted text (https://github.com/metanorma/mnconvert/issues/218)
- [x] ISO/IEC Coding Guidelines: process editing-instruction in MN to STS XML (https://github.com/metanorma/mnconvert/issues/219)
- [x] ISO/IEC Coding Guidelines: table columns width (https://github.com/metanorma/mnconvert/issues/220)
- [x] ISO/IEC Coding Guidelines: table header bold formatting for ISO (https://github.com/metanorma/mnconvert/issues/221)
- [ ] ISO/IEC Coding Guidelines: process roman tag for plain formatting (https://github.com/metanorma/mnconvert/issues/222)
- [x] ISO/IEC Coding Guidelines: table footnote ref-type (https://github.com/metanorma/mnconvert/issues/223)
- [x] ISO/IEC Coding Guidelines: general unit statements in tables  (https://github.com/metanorma/mnconvert/issues/224)
- [ ] ISO/IEC Coding Guidelines: Groups of formulae (https://github.com/metanorma/mnconvert/issues/225)
- [ ] ISO/IEC Coding Guidelines: sub-figures and multiple graphics within a figure for IEC (https://github.com/metanorma/mnconvert/issues/226)
- [x] ISO/IEC Coding Guidelines: Figure key (https://github.com/metanorma/mnconvert/issues/227)
- [x] ISO/IEC Coding Guidelines: Unit statements in figures (https://github.com/metanorma/mnconvert/issues/228)
- [x] ISO/IEC Coding Guidelines: "Part of speech" of a term (https://github.com/metanorma/mnconvert/issues/229)
- [x] ISO/IEC Coding Guidelines: Form of the term (https://github.com/metanorma/mnconvert/issues/230)
- [x] ISO/IEC Coding Guidelines: cross-references to terms external to the document  (https://github.com/metanorma/mnconvert/issues/231)
- [x] ISO/IEC Coding Guidelines: processing tbx:see (https://github.com/metanorma/mnconvert/issues/232)
- [x] ISO/IEC Coding Guidelines: std inside tbx:source (https://github.com/metanorma/mnconvert/issues/233)
- [x] ISO/IEC Coding Guidelines: subject fields of a terminological entry (https://github.com/metanorma/mnconvert/issues/234)
- [ ] ISO/IEC Coding Guidelines: term-display support (https://github.com/metanorma/mnconvert/issues/235)
- [x] ISO/IEC Coding Guidelines: xref @ref-type processing (https://github.com/metanorma/mnconvert/issues/236)
- [x] ISO/IEC Coding Guidelines: footnotes style (https://github.com/metanorma/mnconvert/issues/237)
- [x] ISO/IEC Coding Guidelines: abbreviations lists support (https://github.com/metanorma/mnconvert/issues/238)
- [x] ISO/IEC Coding Guidelines: URL processing (https://github.com/metanorma/mnconvert/issues/239)
- [ ] ISO/IEC Coding Guidelines: table's styles https://github.com/metanorma/mnconvert/issues/240
- [x] ISO/IEC Coding Guidelines: link to supplementary material https://github.com/metanorma/mnconvert/issues/241
- [ ] ISO/IEC Coding Guidelines: footnote with a symbol https://github.com/metanorma/mnconvert/issues/245
- [x] ISO/IEC Coding Guidelines: ID for informal ISO tables https://github.com/metanorma/mnconvert/issues/246

**Comment by Intelligent2013** [comment]
On the page https://www.iec.ch/it-resources updated version is available:
- [NISO STS 1.11 IEC/ISO, XML Coding Guidelines](https://www.iec.ch/system/files/2022-09/Guidelines_for_coding_IEC_and_ISO_standards_in_NISOSTS_v1_11.pdf) (v. 1.11 / 2022-08-10)
with 
- [Addendum to Coding guidelines v.1.5](https://www.iec.ch/system/files/2022-12/Addendum%20to%20Coding%20guidelines%20Official%20v.1.5%20.pdf) (2022-12-14 v.1.5)
- [Addendum to Coding guidelines v.1.5 with revision marks](https://www.iec.ch/system/files/2022-12/addendum-to-coding-guidelines-official-v.1.5-%28revised-file%29.pdf) (2022-12-14 v.1.5)

I'll review them.
